# Form implementation generated from reading ui file '/home/hirdle/Desktop/graph/design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.graphFrame.setGeometry(QtCore.QRect(40, 50, 341, 481))
        self.graphFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.graphFrame.setObjectName("graphFrame")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 60, 121, 16))
        self.label.setObjectName("label")
        self.vertexAddInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.vertexAddInput.setGeometry(QtCore.QRect(420, 80, 171, 22))
        self.vertexAddInput.setStatusTip("")
        self.vertexAddInput.setWhatsThis("")
        self.vertexAddInput.setInputMask("")
        self.vertexAddInput.setText("")
        self.vertexAddInput.setObjectName("vertexAddInput")
        self.vertexAddBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vertexAddBtn.setGeometry(QtCore.QRect(420, 110, 80, 22))
        self.vertexAddBtn.setObjectName("vertexAddBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Добавить вершину"))
        self.vertexAddInput.setPlaceholderText(_translate("MainWindow", "Название вершины"))
        self.vertexAddBtn.setText(_translate("MainWindow", "Создать"))
